# Generated by Django 5.2.8 on 2025-11-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('turma', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=30)),
            ],
        ),
    ]
